### ISSUE TITLE
Could not install in React 18.2.0

### ISSUE THREAD

**Issue by checamon** [wix-incubator/pro-gallery#1001]
It cannot be installed in react 18.

npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from pro-gallery@4.1.76
npm ERR! node_modules/pro-gallery
npm ERR!   pro-gallery@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by yhattav** [comment]
@shmuelhizmi Can we try this with v5?

**Comment by checamon** [comment]
Just made a quick test:
Create-react-app 5.0.1
React 18.2.0"
npm 8.19.2

npm "i" "--save" "pro-gallery"

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test_progallery@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from pro-gallery@5.0.11
npm ERR! node_modules/pro-gallery
npm ERR!   pro-gallery@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by checamon** [comment]
full log:

 verbose cli /usr/bin/n0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.2
2 info using node@v19.4.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/xxxx/E/Documents/test_proGallery/test_progallery/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/xxxx/.npmrc Completed in 1ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/home/xxxx/.npm-global/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i pro-gallery
23 verbose argv "i" "--save" "pro-gallery"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:/home/xxxx/.npm/_logs
28 verbose logfile /home/xxxx/.npm/_logs/2023-01-12T13_21_12_751Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 24ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 840ms
37 timing idealTree:userRequests Completed in 2ms
38 silly idealTree buildDeps
39 silly fetch manifest pro-gallery@*
40 timing arborist:ctor Completed in 0ms
41 http fetch GET 200 https://registry.npmjs.org/pro-gallery 790ms (cache hit)
42 silly fetch manifest react@^18.2.0
43 http fetch GET 200 https://registry.npmjs.org/react 7ms (cache hit)
44 silly fetch manifest react@^16.8.6
45 timing idealTree Completed in 1682ms
46 timing command:i Completed in 1697ms
47 verbose stack Error: unable to resolve dependency tree
47 verbose stack     at [failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1381:25)
47 verbose stack     at [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1347:34)
47 verbose stack     at async [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
47 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
47 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:145:5)
47 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:78:5)
48 verbose cwd /home/xxxx/E/Documents/test_proGallery/test_progallery
49 verbose Linux 5.15.86-1-lts
50 verbose node v19.4.0
51 verbose npm  v8.19.2
52 error code ERESOLVE
53 error ERESOLVE unable to resolve dependency tree
54 error
55 error While resolving: [1mtest_progallery[22m@[1m0.1.0[22m
55 error Found: [1mreact[22m@[1m18.2.0[22m[2m[22m
55 error [2mnode_modules/react[22m
55 error   [1mreact[22m@"[1m^18.2.0[22m" from the root project
55 error
55 error Could not resolve dependency:
55 error [35mpeer[39m [1mreact[22m@"[1m^16.8.6[22m" from [1mpro-gallery[22m@[1m5.0.11[22m[2m[22m
55 error [2mnode_modules/pro-gallery[22m
55 error   [1mpro-gallery[22m@"[1m*[22m" from the root project
55 error
55 error Fix the upstream dependency conflict, or retry
55 error this command with --force, or --legacy-peer-deps
55 error to accept an incorrect (and potentially broken) dependency resolution.
55 error
55 error See /home/xxxx/.npm/eresolve-report.txt for a full report.
56 verbose exit 1
57 timing npm Completed in 1818ms
58 verbose unfinished npm timer reify 1673529672868
59 verbose unfinished npm timer reify:loadTrees 1673529672878
60 verbose unfinished npm timer idealTree:buildDeps 1673529673721
61 verbose unfinished npm timer idealTree:#root 1673529673722
62 verbose code 1
63 error A complete log of this run can be found in:
63 error     /home/xxxx/.npm/_logs/2023-01-12T13_21_12_751Z-debug-0.log

**Comment by owainrutherford** [comment]
Hello, is there a timeline for when pro-gallery will update to react 17 / 18? 
Thanks

**Comment by Gideon755** [comment]
In some cases, you may [need ](https://apkscart.com/naxeex-superhero-mod-apk/)administrator or superuser permissions to install packages globally. Try running the installation command with elevated privileges.

**Comment by EnriquesMar** [comment]
I am facing issues on my website pages you can check here [can someone spy on my internet activity](https://techinstructs.com/how-to-spy-on-internet-activity-through-wifi/), Is there any expert who can guide me to fix those issues?

**Comment by TadeoMakai** [comment]
I was facing this issue on one of my website but successfully resolved it after doing some research I can share here .

**Comment by andarj** [comment]
Need assistance, Facing multiple issues on [https://rainguardroofs.com/](https://rainguardroofs.com/)

**Comment by JamieKrew** [comment]
Facing same installation issue on [MEP Estimation](https://smamepestimate.com/) site.

**Comment by Timothy43** [comment]
React requires Node.js and npm (Node Package Manager) to be installed on your system. Make sure you have them installed [foxynamer](https://foxynamer.com/) and that they are up to date.

**Comment by Bodielas** [comment]
Need assistance, Facing multiple issues on [electrical estimating services](https://www.smaestimating.com/our-trades/electrical-estimating-services/) wesbite.

**Comment by EverettBennett** [comment]
I'm also facing this issue in the same version previous days and need assistance.
https://thoptv-hd.com/

**Comment by RussellNasir** [comment]
Can I apply same code to resolve my [https://focusautodetailing.com/](https://focusautodetailing.com/) website issue?

**Comment by Hankegan** [comment]
Need assistance, Facing multiple issues on [nia vardalos net worth](https://factbasket.com/nia-vardalos/) website.

**Comment by Aqeelfd** [comment]
I implemented this on my [kiritsuke vs nakiri](https://knifeplatoon.com/kiritsuke-vs-nakiri/) site but failed, help needed.

**Comment by Santinoada** [comment]
I'm also facing this issue in the same version previous days on [is 500 paintballs enough](https://truepaintballer.com/how-many-paintballs-you-need/) and need assistance.

**Comment by Kingston34543** [comment]
Need assistance, Facing multiple issues on [bellaboo font](https://getfontfree.com/bellaboo-font/)

**Comment by tomi783** [comment]
Hey everyone! I recently visited [Tomi Sushi](https://tomisushi.org/reservation/) in Singapore and had an amazing dining experience. Has anyone else been there? Let's discuss the food and atmosphere!

**Comment by AlejandraAlanna** [comment]
I have found [lightburn crack](https://www.crackshere.com/lightburn-crack-download/) recently to use premium features without buying any subscription plan.

**Comment by hsrahman1** [comment]
Hello! Guys yesterday I visited Tool [Today New York Times spelling bee answer](https://sbhinter.com/spelling-bee-answers/). This tool can help me become a spelling bee master without spending hours brainstorming. It’s like having a personal spelling bee coach at my fingertips!

**Comment by ThiagoRyker** [comment]
Need assistance, Facing multiple issues on [hack of geometry dash dash](https://geometrydash.pro/geometry-dash-noclip-apk/).

**Comment by ranusami5** [comment]
I implemented this on my [car donations for breast cancer](https://carsforyourhelp.com/government-free-cars-for-cancer-patient/) site but failed, help needed.

**Comment by jaiFowler** [comment]
If possible, try to upgrade the pro-gallery package to a version that supports React 18. This way, you can ensure compatibility with React 18.2.0. [Capcut Mod APK](https://capcutmods.org/)
Downgrade React:

If you must use the specific version of pro-gallery that requires React "^16.8.6", you may need to downgrade your React version to 16.8.6 or a compatible version.

**Comment by allen749875** [comment]
Hey everyone! 👋 Has anyone been to [33 Blue Room](33blueroom.org/) Restaurant in Malaysia? I've heard some great things about their unique menu and vibrant ambiance. Thinking of checking it out this weekend. Any recommendations?

**Comment by sanganimedia1** [comment]
React 18 introduces changes incompatible with dependencies like pro-gallery@4.1.76, requiring React "^16.8.6". You can't install pro-gallery due to the conflict between React versions. Resolve by updating pro-gallery or finding a compatible version supporting React 18. Consider --force or --legacy-peer-deps for temporary [solutions ](https://www.alexcar.com/) with potential risks.

**Comment by salinakyle** [comment]
I am having the same kind of vague issues on my page [roblox mod apk ghost mode](https://apkcroc.com/roblox-mod-apk/) can anyone help?

**Comment by allen749875** [comment]
In the vibrant culinary landscape of Singapore, [Ah loy thai](https://ahloythai.org/) Restaurant and [Fatty Bom Bom](https://fattybombom.org/) have emerged as popular establishments, each offering a unique dining experience. This formal discussion aims to compare and contrast the two, shedding light on their distinct characteristics, culinary offerings, and overall appeal to discerning diners.

**Comment by Daniela5423Leia** [comment]
I'm also facing same code of error while installing react on system.. is that [Geometry Dash APK](https://www.google.com/url?q=https://www.thegeometrydashapk.com/&sa=D&source=editors&ust=1706528597060903&usg=AOvVaw1fCNegO3v2Q9trivVkP3yH) providing solution working?

**Comment by thegeometrydashapk** [comment]
I was also facing these issues with [Geometry Dash in 2024](https://thegeometrydashapk.com/) and it took me a while to solve these issues!

**Comment by burgermenuprice** [comment]
Have you checked the React documentation or release notes to see if there are any known issues or compatibility issues with the version you're trying to install?

**Comment by ameliaava12** [comment]
I was having the same problem with the same version a few days ago.
Regard: [Hearts](https://animallearns.com/how-many-hearts-do-cows-have/)

**Comment by c4pcut** [comment]
you can download from here [Capcut APK](https://capcutapkdownload.org/)

**Comment by salinakyle** [comment]
Another same issue we're experiencing on website [vat calculator](https://vatcalculatorpro.co.uk/) website.

**Comment by hasanakmal1** [comment]
I am also facing similar kind of issues with my [Alight Motion Mod APK Website](https://alightmotionproapks.net/). Has anyone found a proper solution for this issue?

**Comment by Aaravbbon** [comment]
We're facing a similar problem with the Car Parking Multiplayer 2 [website](https://cpmapk.com/car-parking-multiplayer-2-mod-apk/). It's frustrating that we can't download the game from there either. Let's hope they fix it soon so everyone can enjoy playing.

**Comment by salinakyle** [comment]
Wondering what should i do with the website [carx street mod apk unlimited money](https://carxstreetapkz.com/) quickly?

**Comment by Fontbugg** [comment]
I need the help of any expert, I have many problem and issues related My website **[Fontbugg.com](https://fontbugg.com/)** i want  some changes in my site. thank you.

**Comment by Fontbugg** [comment]
I need some help of any expert regarding my website **[Fontbugg.com](https://fontbugg.com/)**, I want some changes in my site.

**Comment by assignmentsold** [comment]
"The Canadian[ real estate market ]([url](url))offers a distinctive approach to property transactions through a method known as the 'assignment sale.' Platforms like https://assignmentsold.ca/ facilitate these transactions by connecting buyers and sellers of assignment properties. In an assignment sale, the original buyer (assignor) transfers their rights and obligations under the purchase agreement to a new buyer (assignee) before the official closing date of the property. This process is particularly common in the pre-construction real estate sector. This assignment seeks to provide a thorough understanding of Assignment Sold, exploring their legal implications, benefits, and challenges within the Canadian context."

**Comment by poolking63** [comment]
[MoviesFlix](https://movies-flix.online/) is your ultimate destination fr discovering and streaming the latest movies and TV shows. Enjoy a diverse collection of films across genres, with high-quality streaming and a user-friendly experience. Dive into your next cinematic adventure with MoviesFlix!

**Comment by allanpottss** [comment]
It’s frustrating when these compatibility issues pop up, especially when you're working on projects like [custom designed lifting belts](https://www.genghisfitness.com/shop/products/custom-designed-lifting-belts/) site. I had a similar issue while trying to integrate certain libraries, and it really slowed down the progress. It’s crucial to ensure all dependencies are compatible to avoid these hiccups. I hope there’s an update or workaround soon that can help us all out.

**Comment by poolking63** [comment]
[MoviesFlix](https://movies-flix.online/) is your ultimate destination for discovering and streaming the latest movies and TV shows. Enjoy a diverse collection of films across genres, with high-quality streaming and a user-friendly experience. Dive into your next cinematic adventure with MoviesFlix!

**Comment by yhattav** [comment]
Should work in version 5

**Comment by beon123** [comment]
In the fast-changing world of digital photography, the lines between professional and amateur work are increasingly blurred. With the advent and rampant growth of smartphone [photoleap mod apk](https://blastapks.com/photoleap-mod-apk/) photography, post-processing no longer belongs exclusively to the realm of professionals.

**Comment by junaidAccount** [comment]
[Exotic Genetix](https://www.cannapot.com/shop/hanfsamen/exotic-genetix/) is a prominent cannabis seed company known for creating unique and high-quality cannabis strains. Founded by a breeder known as Mike, the company has gained recognition for its innovative breeding techniques and the development of award-winning strains.

**Comment by john-mcarthyyy** [comment]
If you're searching for the perfect [Leavers Hoodie](https://www.pprints.co.uk/page/leavers-hoodies) PPrints is your go-to solution! We specialize in creating custom hoodies that reflect your unique style and personality. Whether it's for school leavers, university events, or corporate wear, we offer a wide variety of hoodie options to choose from. With competitive prices and a simple online design tool, it's easier than ever to create something truly special. You can even mix styles, sizes, and colors to get exactly what you need. Contact us today for a free sample and personalized quote.

**Comment by zain140** [comment]
this is good to check this solution:https://fluxusteamexecutor.com/

**Comment by zain140** [comment]
good information to check this <a href="https://fluxusteamexecutor.com/">check this</a>

**Comment by williamsammer** [comment]
With [Fire Kirin](https://thefirekirinapk.com/) you can dive into an underwater world filled with fun fish-shooting action and unique rewards. It’s perfect for any fan of arcade games who loves great visuals.

**Comment by hasanakmal1** [comment]
Facing same kind of issue on my [Geometry Dash 2.2](https://thegeometrydashapks.com) website. Any proper solution for this?

**Comment by tgraphyco** [comment]
Running into installation issues can be super frustrating — we had similar problems setting up a React-based gallery system for our [corporate photography Dubai](https://www.thephotographyco.ae/portrait-headshot-photography) website. Keeping Node and npm versions aligned across environments helped stabilize things. If you're building anything media-heavy, it’s worth testing locally before pushing to production.

**Comment by ijaz155** [comment]
<a href="https://beetvapks.app/">    beetv app </a> is a movie & video streaming app that brings the latest & free streaming content from global entertainment brands like Netflix, Prime Videos, Hotstar, ...

**Comment by ijaz155** [comment]
Download<a href="https://cricfytvs.app/">    Cricfy TV Apk  </a> optimized for Android 6. Enjoy seamless streaming and excellent performance on older devices.

**Comment by shawn-rothh** [comment]
Noticed [gold365](https://gooold365.com/) getting mentioned in a few Telegram groups and finally decided to give it a go. It feels pretty polished and doesn’t overload you with ads or clutter, which I appreciated. I’ve mostly stuck to cricket matches, but I saw options like Teen Patti and roulette too. They’ve clearly covered a lot of ground. It’s been a surprisingly smooth ride so far.

**Comment by john668145-ctrl** [comment]
I just checked out this Little Caesars menu & pricing guide — it’s got all the Hot‑N‑Ready pizzas, pretzel crusts, sides, and combo deals clearly laid out with photos and prices . Super helpful if you’re trying to budget your next pizza run. Worth a look if you’re craving some cheesy goodness! Check it out here: https://littlecaesars-menu-prices.com/

**Comment by john668145-ctrl** [comment]
Just browsed through the Panera Bread menu and prices — everything’s super organized, from soups and salads to sandwiches and drinks. Makes it easy to plan ahead before heading out or ordering online. Definitely helpful for regulars or first-time visitors!
Check it out here: https://panerabread-menu-prices.com/

**Comment by john668145-ctrl** [comment]
I found the Del Taco menu and prices super easy to navigate — they’ve got everything listed clearly, from tacos and burritos to breakfast and drinks . Great resource if you want to check prices before you order or try something new. Take a look here: https://deltaco-menu.site/

**Comment by livirafashion01** [comment]
I faced the same issue trying to install pro-gallery with React 18 because it only supports React 16.8.6 as a peer dependency, so the install fails unless you use --legacy-peer-deps. Hopefully the maintainers update support for React 17/18 soon. In the meantime, while working on design projects, I drew some inspiration from fashion sites like this [Elegant mini dress](https://livirafashion.com/)
 collection, which reminded me how important clean and modern styling is when everything else feels stuck.

**Comment by livirafashion01** [comment]
I ran into the same dependency issue when trying to set up pro-gallery on a React 18 project. Using --legacy-peer-deps worked as a quick fix, but it’s not ideal long-term since it may break with future updates. Hopefully the maintainers will push React 18 support soon. In the meantime, I shifted focus back to styling and layouts — drew some ideas from [Saint Barth MC2](www.am2store.com)
 collections, which really reminded me how important clean design is when working around technical limitations.

**Comment by manahilasad680-afk** [comment]
Auto Farm Grow a Garden Script is a Roblox script that makes farming in the Grow a Garden game automatic and easy. With this script, players can collect items, grow plants, and level up without doing everything by hand. It saves time and makes the game faster, but like other scripts, it should be used carefully to avoid account bans or problems.
https://speedhubgrowagarden.com/

**Comment by mahadevvbook** [comment]
Someone on a forum recommended trying [mahadev book registration](https://mahadevvboook.com/), and I gave it a shot. Honestly, it worked seamlessly. I didn’t face any hiccups or errors. That kind of reliability is worth mentioning.

**Comment by wibewave668-star** [comment]
If you’re looking for strong legal representation in Coral Gables, hiring a [Coral Gables criminal defense attorney](https://espinosalaw.com/)
 is essential. Facing criminal charges can be overwhelming, and an experienced attorney provides guidance, defends your rights aggressively, and builds a strategy tailored to your case. From white-collar crimes to serious offenses, having skilled legal support ensures you’re prepared for every step of the legal process. Don’t navigate it alone Expert counsel can make a critical difference.

**Comment by lotuss365service** [comment]
I tried out [Lotus365](https://www.lotus365service.com/) recently and noticed how reliable the system is. It doesn’t lag or crash, which is something I really value. It gives a sense of professionalism and trust that’s sometimes missing from other platforms.

**Comment by ananyaabachan** [comment]
[Vedu app](https://vduapkdl.com) is truly one of the best streaming apps out there! 🎥 It combines speed, reliability, and high-quality HD streaming to deliver an amazing entertainment experience. Unlike many other apps, it’s completely ad-free, so you can enjoy movies, TV shows, and series without any interruptions. The app’s smooth interface makes browsing super easy, and its massive collection covers every genre—from action and drama to comedy and romance. Whether you’re at home relaxing or traveling on the go, Vedu ensures you’ll always have access to endless, high-quality entertainment at your fingertips. 🌟🚀

**Comment by Johnesjensonss** [comment]
While discussing IPL and PSL excitement, [Lotus365](https://lotus365ss.com/) frequently appears as a trending name among fans. The platform blends live action with entertaining challenges. Smooth performance ensures uninterrupted participation. It adds a new dimension to following favorite teams.
