### ISSUE TITLE
How to center Thumbnails? And how to open full screen.

### ISSUE THREAD

**Issue by PremExtensi** [wix-incubator/pro-gallery#1082]
Is there a way to center Thumbnails?
And how to open full screen?
Is there any kind of documentation?

**Comment by yhattav** [comment]
Hey,
There is no built in fullscreen component. 
You can use the ITEM_ACTION_TRIGGERED event to create a trigger for a fullscreen component as part of a wider application.
Cant center the thumbnails as they are, we are open to contributions on thumbnails and documentation.
