### ISSUE TITLE
Images are flipping / changing

### ISSUE THREAD

**Issue by zxhmike** [wix-incubator/pro-gallery#1111]
Hi there,

This is an awesome project. It is feature rich (videos!) and the themes are very nice. 

However, when I am in the [playground](https://pro-gallery.surge.sh/?layoutParams_structure_galleryLayout=0&behaviourParams_item_clickAction=MAGNIFY) and it seems like lazy loading is having some issues. When I scroll up and down, the images on the bottom right keep changing / flipping. There are sometimes duplicated pictures as well. Please refer to the screen recording below.

https://user-images.githubusercontent.com/4087876/221371061-28b0d69b-561d-456a-8016-69783268d338.mov

I can replicate this issue on my phone as well. Is this intentional? I tried to search among the past issues and did not find similar situations so far. I am happy to take a look and try to fix it if it can be confirmed by others. Thanks.

**Comment by yhattav** [comment]
Hey, Happy to hear you enjoy this project.
This could be a bug in the playground itself (rerendering the gallery with new images) It looks like they images in your video change entirely (not all of them but from a certain point).
We do know that we have a few issue that make the playground hard to use but currently we don't have the ability to work on the playground itself.

**Comment by robert-micheal** [comment]
To resolve the issue you can do the following things:
Implement image preloading to avoid duplication and flickering.
Verify image source and loading for correctness.
Optimize lazy loading implementation.
Conduct thorough testing across browsers and devices for consistent performance.
Collaborate with the development team to diagnose and resolve the issue promptly.

**Comment by DAINY123** [comment]
Hi, thanks for your feedback. It seems like there might be a bug with lazy loading, you can check [this site](https://weltvermoegen.de/claudia-roth-vermoegen/) for more clarification. Please check your code for any issues and consider optimizing the lazy loading implementation.

**Comment by EmilyThompson23** [comment]
If images are flipping or changing unexpectedly, as indicated by issue #1111, it could be due to CSS transformations, JavaScript conflicts, or image-loading issues. Check your CSS for any transform properties or animations that might affect image orientation. Review your JavaScript code for functions that manipulate images. Additionally, ensure that images are being loaded correctly and are not subject to caching issues. Debugging with browser developer tools can help identify the root cause and resolve the problem.
