### ISSUE TITLE
Playground options gives parsing error

### ISSUE THREAD

**Issue by ChulChong** [wix-incubator/pro-gallery#1125]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/62628427/229880308-e63bb598-5909-4692-8a33-2baed8efde03.png">

>SyntaxError: /Users/chulchong/cs/wedding/src/Components/Gallery.js: Unexpected token (17:4)
  15 |
  16 |   const options = {
 17 |     {
     |     ^
  18 |         "layoutParams": {
  19 |             "structure": {
  20 |                 "galleryLayout":

 ```
 const options = {
    {
        "layoutParams": {
            "structure": {
                "galleryLayout": 1
            },
            "targetItemSize": {
                "value": 80
            }
        },
        "behaviourParams": {
            "item": {
                "overlay": {
                    "hoveringBehaviour": "NEVER_SHOW"
                },
                "content": {
                    "hoverAnimation": "COLOR_IN",
                    "loader": "COLOR"
                }
            },
            "gallery": {
                "scrollAnimation": "SLIDE_UP"
            }
        }
    }
        };
```

**Comment by ChulChong** [comment]
The older option syntax is not working as well
```
const options = {
    galleryLayout: 0,
    collageDensity: "0.1",
    galleryMargin: 10,
    hoveringBehaviour: "NEVER_SHOW",
    imageHoverAnimation: "ZOOM_IN",
    gallerySize: 100,
    imagePlacementAnimation: "SLIDE",
  };
```

**Comment by yhattav** [comment]
Hey,
We will probably need to update this representation.
Could you please try to use a flat version of these?
You can use this:
import { flattenObject } from 'pro-gallery-lib';
It will take your object (which we know is much more readable), and flatten it to:
{...
"layoutParans_structure_galleryLayout": 0
...}

The old naming of version 4 doesnt exist anymore.

**Comment by nickwe3** [comment]
As of today, it's still the only option to change layout for me.

Otherwise it's collage by default whatever galleryLayout I choose.

**Comment by dnspnjrs** [comment]
Same for me. Passing options to the component does not change layout.

@nickwe3 Found the solution. You can read about it [here](https://github.com/wix-incubator/pro-gallery/blob/master/v5_migration.md).

Correct way of passing options:
` 
const options = {
    layoutParams_structure_galleryLayout: 4,
};`

Goodluck!

**Comment by nickwe3** [comment]
Wonderfull ! Thanks @dnspnjrs !
