### ISSUE TITLE
Provide url in runtime (when dimensions are known)

### ISSUE THREAD

**Issue by naorye** [wix-incubator/pro-gallery#211]
Is there a way to provide the image url in runtime, when the item dimensions are know?
This way I will be able to download image with precise dimensions instead of just big image (for example, when I am using Cloudinary).

I saw there is `createUrl` method of item but I haven't seen any straight forward way to inject / override that property.

Thanks

**Comment by guysopher** [comment]
Hey, 
You can provide a `resizeMediaUrl` function that will get the current item and dimensions as parameters and return the resized URL.
I noticed it is not in the docs, we will add it.
