### ISSUE TITLE
npm i -S pro-gallery not working

### ISSUE THREAD

**Issue by ChTayyab786** [wix-incubator/pro-gallery#300]
PS E:\interior> npm i -S pro-gallery
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree  
npm ERR! While resolving: lacasa-interior@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.6" from pro-gallery@3.1.11
npm ERR! node_modules/pro-gallery
npm ERR!   pro-gallery@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Cy\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cy\AppData\Local\npm-cache\_logs\2021-04-29T09_23_42_698Z-debug.log

**Comment by abdulrahimiliasu** [comment]
Try this
```
npm i -S pro-gallery --legacy-peer-deps 
```
