### ISSUE TITLE
[createLayout] Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ccpu** [wix-incubator/pro-gallery#419]
Trying to run example of `layouts` package, but it throws following error:

` Cannot read property 'indexOf' of undefined`

[Here is the codesandbox example](https://codesandbox.io/s/infallible-mclaren-h6u05?file=/src/index.js:9-21)

**Comment by yhattav** [comment]
Hey, Can you take a look at the item format that the PG expects? You can use the playground and it's code.
Furthermore, you can now use the blueprints package which wraps all the logic around the formatting of the container, options, items and returns the blueprint: {items, options, dimensions, structure} where the structure is the layout the the layouter created from those arguments.
