### ISSUE TITLE
enable lightbox ("expand image") option while not on simulator mode

### ISSUE THREAD

**Issue by nelhwong** [wix-incubator/pro-gallery#429]
I see there's an option for a light box in the simulator mode but I'm not sure on how to enable it using the options prop. 
![image](https://user-images.githubusercontent.com/47463908/127756449-93a41726-a4f6-47fb-bed1-e574ff3e9176.png)

**Comment by mikemajara** [comment]
@nelhwong did you find the way to set this in your code? This is asked too in https://github.com/wix/pro-gallery/issues/573, and there does not seem to be a clear solution

**Comment by mustlovemelissa** [comment]
@mikemajara did you by any chance find a solution to this?

**Comment by yhattav** [comment]
Hey,
the expanded image component is not planned to be a part of the pro-gallery bundle.
In the simulator we use a simple component we created for the expand mode.
It is triggered by the gallery with the help of the eventsListener function frovided in the props.
This callback will trigger on clicks on an item if the option for itemClick is set for expand/fullscreen.
In the next version of the gallery we are planning on deprecating these options and using a 1-for-all 'action' option to replace expand/fullscreen' as these are indeed not gallery logic.
