### ISSUE TITLE
Title and description don't show up on hover

### ISSUE THREAD

**Issue by strandchef** [wix-incubator/pro-gallery#539]
Hello all,

Thank you for the great work on this gallery component!

If i use the code from the playground, i don't get to work, that the title and the description of the image are shown on hover. I think i might be doing something wrong, and this is no github  issue, but as nobody could help me, i try it here.
Sorry, if it is the wrong place.
I used this code:

https://stackblitz.com/edit/react-ts-6f9ovv?file=Gallery.js

Any help would be appreciated, thanks!

**Comment by nechmads** [comment]
Same here. Title and description never show (using React 17).

**Comment by 6a616e** [comment]
You need to define a `customHoverRenderer`:

```javascript
  const customHoverRenderer = (itemMetadata) => (
    <div>
        <p>{itemMetadata.description}</p>
        <p>{itemMetadata.title}</p>
    </div>
  );

  return (
    <ProGallery
     /* ... */
      customHoverRenderer={customHoverRenderer}
    />
  );
```

Full example: https://stackblitz.com/edit/react-ts-r1utva?file=Gallery.js

Hope this helps!
I really like the features of this library, but the missing documentation and the need to reverse engineer almost every feature is driving me crazy.

**Comment by strandchef** [comment]
Thank you very much! This is exactly what i was looking for...

**Comment by EngineNeo** [comment]
I am unable to reproduce the successful onHover `customHoverRender` prop  

I first tried both of the code you provided. I then tried this:

```
  const customHoverRenderer = (items) => (
    <div>
        <p>{items.metaData.title}</p>
        <p>{items.metaData.description}</p>
    </div>
  );
```

However, this still did not work, I was wondering if this prop was updated as to have a different functionality than previously mentioned.
