### ISSUE TITLE
option for Click to Expand

### ISSUE THREAD

**Issue by abdulrahimiliasu** [wix-incubator/pro-gallery#573]
The gallery is great, but can't seem to find any documentation on **click to Expand**, even though it is available on the simulator.

I tried using hoping it works, but didn't.

```javascript
const options = {
    galleryLayout: 3,
    scrollAnimation: "SLIDE_UP",
    clickToExpand: "SITE", //here
    hoveringBehaviour: "NEVER_SHOW",
  };
```

**Comment by yhattav** [comment]
Hey,
the expanded image component is not planned to be a part of the pro-gallery bundle.
In the simulator we use a simple component we created for the expand mode.
It is triggered by the gallery with the help of the eventsListener function frovided in the props.
This callback will trigger on clicks on an item if the option for itemClick is set for expand/fullscreen.
In the next version of the gallery we are planning on deprecating these options and using a 1-for-all 'action' option to replace expand/fullscreen' as these are indeed not gallery logic.
