### ISSUE TITLE
activeIndex not working

### ISSUE THREAD

**Issue by denny7** [wix-incubator/pro-gallery#599]
Hello! I'm trying to implement expandable gallery. I've followed the example in github. I'm facing issue with activeIndex prop that I pass to my fullscreen gallery. It seems it doesn't work. Every time when I open my fullscreen gallery it starts from beginning. I'm using : 
```
  galleryLayout: 3,
  cubeType: 'max',
  ...
```

**Comment by Fmstrat** [comment]
Were you ever able to get this working?

**Comment by robert-micheal** [comment]
Hello! To resolve the issue with the activeIndex prop in your fullscreen gallery, you can try the following steps:

Verify Active Index Value: Double-check that the value you're passing to the activeIndex prop is correctly set and matches the index of the image you want to start with in the gallery.

Update Gallery Component: Ensure that the fullscreen gallery component is properly receiving and utilizing the activeIndex prop. Check for any discrepancies in the component code that might be causing the issue.

Synchronize Gallery Layout: Confirm that the galleryLayout and cubeType properties are compatible with the activeIndex prop. In some cases, certain layout or cubeType configurations might affect the activeIndex behavior.

**Comment by ErmiasJoe** [comment]
Have you best solution of [s9 game apk 2024](https://s9gamedownload.com/) for activeindex?
