### ISSUE TITLE
Loop mode in Thumbnail gallery

### ISSUE THREAD

**Issue by denny7** [wix-incubator/pro-gallery#600]
Hello. Is there any way to implement loop mode in thumbnail gallery?

**Comment by yhattav** [comment]
you can use the [behaviourParams_gallery_horizontal_loop](https://github.com/wix/pro-gallery/blob/master/packages/lib/src/settings/options/behaviourParams_gallery_horizontal_loop.js) (boolean) to loop in horizontal galleries.
