### ISSUE TITLE
Next.js < Image >

### ISSUE THREAD

**Issue by codcodea** [wix-incubator/pro-gallery#680]
Hi nice work! 

I'm trying to pass Next.js: custom < Image > render component to

customComponents={{
      customImageRenderer={imageProps => <Image {...imageProps} />}
  }} 

(...replacing <img with <Image)

Get Error:
Error: failed to process internal error: entered unreachable code: assign property in object literal is invalid.

Not sure if the issue is on my side, or if it is a bug? :-)

**Comment by kentnhi** [comment]
``` javascript
customComponents={{
	customImageRenderer: (imageProps) => {
		return (
			<Image
			src={imageProps.src}
			height={imageProps.style.height}
			width={imageProps.style.width}
			/>
		)
     },}}`

**Comment by kentare** [comment]
I could not find a way to pass metatags, which would be useful for showing placeholder data while the image loads

But you can use the Image component it like this: 
``` javascript
customComponents={{
	customImageRenderer: (imageProps) => {
		return (
			<Image
			src={imageProps.src}
			height={imageProps.style.height}
			width={imageProps.style.width}
			/>
		)
     },
}}`

**Comment by yhattav** [comment]
Hi @kentare 
Sorry for our late response.
Can you clarify about the metatags? Maybe even a link so we can read more and see if we can help.

**Comment by Luciano564** [comment]
The error message you're encountering suggests that there is a syntax issue in the way you're defining the customImageRenderer property in the customComponents object. It appears that there might be a syntax error or incorrect structure in your code.

In JavaScript object literals, you should define properties without the assignment operator (=). Instead, you should specify the property name [advancedcardetailing](https://advancedcardetailing.com/) followed by a colon (:) and then provide the property value.
