### ISSUE TITLE
Use with react-native and Android compile (window.screen.width error)

### ISSUE THREAD

**Issue by Fmstrat** [wix-incubator/pro-gallery#899]
When building `pro-gallery` inside an `expo` created `react-native` Android app, compilation completes but running the app causes things to crash. The error reported is:
```
07-27 11:35:59.921 26627 26656 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-27 11:35:59.921 26627 26656 E AndroidRuntime: Process: com.nowsci.nowgallery, PID: 26627
07-27 11:35:59.921 26627 26656 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 't.window.screen.width'), stack:
07-27 11:35:59.921 26627 26656 E AndroidRuntime: o@725:305
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@725:6189
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@716:245
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@714:196
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@713:206
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@711:176
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@489:176
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@488:327
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@487:2209
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@476:557
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: <unknown>@6:57
07-27 11:35:59.921 26627 26656 E AndroidRuntime: h@2:1585
07-27 11:35:59.921 26627 26656 E AndroidRuntime: d@2:958
07-27 11:35:59.921 26627 26656 E AndroidRuntime: global code@930:3
07-27 11:35:59.921 26627 26656 E AndroidRuntime: 
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
07-27 11:35:59.921 26627 26656 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
```
I believe this is due to the use of `window.screen.width` at all times, even if not executing in a browser.

**Comment by Fmstrat** [comment]
Note, this happens as soon as this is added to the app:
```
import { ProGallery } from 'pro-gallery';
```

**Comment by Fmstrat** [comment]
[EDIT] The login expired causing me to think this wasn't an issue, but it is.

**Comment by Fmstrat** [comment]
I'm guessing the issue originates here: https://github.com/wix/pro-gallery/blob/d86201843c6f1cd9e3dca8cfdcc89519f0c2ca96/packages/lib/src/common/window/windowWrapper.js#L17

This element from `windowIsAvailable` ...
```javascript
        try {
            return typeof window !== 'undefined';
        }
        catch (e) {
            return false;
        }
```
... likely returns a `window` object when compiled that does not contain the `screen` element required when running in native mode. A solution might be to include at the top:
```
import { Dimensions } from 'react-native';
```
and then use a Mock or create some other window object with the screen sizes set using `Dimensions.get('screen').width`

**Comment by Fmstrat** [comment]
I would try to do a PR, but https://github.com/wix/pro-gallery/issues/900 is blocking me and I'm not sure where to go to get a clean build (or why it's trying to download the lib vs compile to begin with, for that matter). Just my inexperience with this library setup unfortunately.

**Comment by Fmstrat** [comment]
I've confirmed this is the case by editing the JS in the APK. If I add `window.screen={width:200,height:200}` the app no longer crashes, but of course the sizing is off.

**Comment by Moiseskhan9080** [comment]
To resolve this issue, you'll need to use React Native's built-in methods for obtaining screen dimensions. You can [use essay on atomic energy](https://studiesea.com/essay-on-atomic-energy/essay-writing/) the Dimensions module from the React Native library to get the width of the screen. Here's how you can do it:
import { Dimensions } from 'react-native';

// Get the dimensions of the screen
const screenWidth = Dimensions.get('window').width;

**Comment by evelynemma22** [comment]
You'll need to use React Native's built-in screen dimensioning APIs to overcome this problem. To get the width of the screen, use the Dimensions module from the React Native library, as explained in the essay on atomic energy. Here's how to accomplish it:
'react-native' imports { Dimensions};
Regard: [Panther](https://animallearns.com/are-black-panthers-dangerous/)

**Comment by coralalbert** [comment]
The window.screen.width error in React Native typically occurs because window is a web-specific object and not available in React Native. For cross-platform development, use React Native's Dimensions API to get the screen width on Android and iOS. You can access it with const screenWidth = Dimensions.get('window').width;. This will give you the screen dimensions in a React Native environment without causing errors during Android compilation.

**Comment by yhattav** [comment]
the mock window object should be returned in screenless environments (like SSR). it should not be the case in the client. The gallery was made for web browsers.
