### ISSUE TITLE
Doesn't show all items when inside an overflow: scroll div

### ISSUE THREAD

**Issue by hashwarp** [wix-incubator/pro-gallery#947]
It seems like showing items requires the body to be scrolling, otherwise it will never show more than the initial page width/height of items. Doesn't matter if you add more via NEED_MORE_ITEMS or just pushing them into the array.

**Comment by yhattav** [comment]
For vertical infinite gallery settings you need the wrapping component to grow with the gallery.
For horizontal ones you need to work with the scrollingElement so that the scroll triggers apply (and the get more items work).
