### ISSUE TITLE
How to make it work with next.js ?

### ISSUE THREAD

**Issue by da1z** [wix-incubator/pro-gallery#948]
I am getting this error in next js:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

I am using your example code

```
    const container = {
        width: 1280,
        height: 1000,
    };
                    <ProGallery
                        id="gallery"
                        isPrerenderMode={typeof window === 'undefined'}
                        items={items}
                        options={options}
                        container={container}
                    />
```

**Comment by yhattav** [comment]
Hey, notice that prerender mode should include the hydrate stage.
In your example you make isPrerenderMode === isServerSideREndering which will create this exact issue.
isPrerenderMode was created to be true when the imformation that is used in the server/hydrate to create the gallery is still not whole.
As the most common example, if you use the gallery in a responsive manner (1vw) you will not know the window width in the server(window undefined) and before measuring it (hydrate). 
If this is the case isPrerenderMode should be true (server) true (hydrate) and change to true only after setting the correct dimensions (render).
