### ISSUE TITLE
Uncaught (in promise) ReferenceError: global is not defined

### ISSUE THREAD

**Issue by jruiz94** [wix-incubator/pro-gallery#973]
I have some issues trying to make this work with Astro.js. I've created a default project with `yarn create astro` then added the React integration with `yarn astro add react` then copied the default example code present in the Github main page into a new `Gallery.jsx` file and imported it into a new astro page (it is needed to add the `client:only="react"` directive to the component in order for it to be client-side rendered only)

I checked the console and it threw an error
```
Uncaught (in promise) ReferenceError: global is not defined
    isSSR index.js:339
    shouldUseCache index.js:22
    getOrPutFromCache index.js:74
    isiOS index.js:363
    <anonymous> videoItemWrapper.js:8
```

For reference this is the `index.astro` file
```
---
import Layout from '../layouts/Layout.astro';
import {Gallery} from '../components/Gallery';
---

<Layout title="Welcome to Astro.">
	<main>
		<h1>Welcome to <span class="text-gradient">My gallery</span></h1>
		<Gallery client:only="react"/>
	</main>
</Layout>
```
I'd also copy paste the `Gallery.jsx` file but its the exact same as the code that is on the main github page, so it does not make sense to copy it here.

**Comment by jruiz94** [comment]
Perhaps it has something to do with `isPrerenderMode`? I've tried to set it to true but doesn't seem to affect it. 
I tracked down the error and it seems to originate here
```
// TODO : Replace with `isPrerender` mode
Utils.prototype.isSSR = function () {
    return typeof global.window === 'undefined';
};
```
Could this be replaced with the `isPrerenderMode` variable? Thanks in advance

**Comment by jruiz94** [comment]
I definitely fixed this by returning true on the above mentioned function (instead of using the variable name)

I'm too noob to open a PR (can't find the pro-gallery-lib repo), could somebody do it?

**Comment by yhattav** [comment]
Hey,
I am not sure I understand.

About the docs, they might be outdated. The gallery is undergoing a lot of changes and we should get to it soon.

isPrerenderMode is intended to cover both ServerSideRendering and Hydrate stages of the web application (React) where the final dimensions of a gallery might be unknown (screen size in the server etc.). If you are rendering the gallery in the client only and have exact unchanging dimensions (or don't care about layout shifts) you can just assign true to the isPrerenderMode prop.

**Comment by jruiz94** [comment]
Thanks for taking the time to answer. I was a bit frustrated and I probably explained myself poorly. Sorry about that.

So, using the ProGallery playground, I created the following file
`GalleryReact.jsx`
```javascript
import { ProGallery } from 'pro-gallery';
import 'pro-gallery/dist/statics/main.css';

export function GalleryReact() {

    // Add your images here...
    const items = [. . .]


    // The options of the gallery (from the playground current state)
    const options = {. . .}
	

    // The size of the gallery container. The images will fit themselves in it
    const container = {
		width: window.innerWidth,
		height: window.innerHeight
    };

    // The eventsListener will notify you anytime something has happened in the gallery.
    const eventsListener = (eventName, eventData) => {
		console.log({eventName, eventData});
	};

    // The scrollingElement is usually the window, if you are scrolling inside another element, suplly it here
    const scrollingElement = window;

    return (
		<ProGallery
			id={"test-gallery"}
			items={items}
			options={options}
			container={container}
			eventsListener={eventsListener}
			scrollingElement={scrollingElement}
		/>
    );
}
  // Enjoy using your new gallery!
  // For more options, visit https://github.com/wix/pro-gallery
```

Then created an Astro page including that component.
`test.astro`
```
---
import Layout from "../layouts/Layout.astro";
import { GalleryReact } from "../components/gallery/GalleryReact.jsx";
import Header from "../components/Header.svelte";
import Footer from "../components/Footer.astro";
---

<Layout title="test">
    <Header client:load/>
    <main>
        <div class="container mx-auto pb-5">
            <GalleryReact client:only="react"/>
        </div>
    </main>
    <Footer/>
</Layout>
```
`client:only="react"` is an astro directive that makes the component to be rendered on the client. This was done because otherwise it would complain that `window` didnt exist (which makes sense because part of the rendering is done on the server)

However, it still gave me an error in the console, stating that `global` was not defined. I tracked down where in `pro-gallery` code was `global` being used and I found that it was being used in the following function
`index.js`
```javascript
. . . 
// TODO : Replace with isPrerender mode
    Utils.prototype.isSSR = function () {
    return typeof global.window === 'undefined';
};
. . .
```
So what I've done to fix this is to basically change the `return` to simply `return true` and now the gallery works. It seems also to be working when I return `false` so I don't quite understand how it changes anything in the gallery, but as long as the images show up, for me it's ok.

Setting `isPrerenderMode` to `true` seems to make the gallery to not render, so I left it at default value which is false.

Sorry for my previously misleading comments, however, the issue with the `global` variable being undefined is still there in case you want to check that, perhaps.

Thanks again

**Comment by yhattav** [comment]
Thanks for clarifying.
I see that there were intentions to replace the isSSR (which is specific in the way it answers) with the isPrerenderMode which depends on external input (better IMO, as it lets the user decide how the gallery behaves).

the isPrerenderMode true should not cause the gallery not to render but instead, it makes everything opacity: 0. so it's not visible. With advanced tricks, you can have scripts on the dom calculate the final dimensions and set opacity:1 with the correct dimensions even before the app is loaded.

I wrote a PR to protect the global call in this (currently still) used function 
https://github.com/wix/pro-gallery/pull/981
It should do the trick for now.

**Comment by jruiz94** [comment]
Thanks a lot!

**Comment by yhattav** [comment]
Merged. Please let me know if this fixes the issue.

**Comment by jruiz94** [comment]
Hi sorry to disturb you again. I updated pro-gallery to version 4.1.71 by running `yarn remove pro-gallery` then `yarn add pro-gallery` but the unprotected access to `global` is still there, so I'm getting the same error.

For context I'm opening up the file `node_modules/pro-gallery-lib/dist/cjs/common/utils/index.js` and there's still the function
```
// TODO : Replace with isPrerender mode
Utils.prototype.isSSR = function () {
    return typeof global.window === 'undefined';
};
``` 
without the `global?` that you merged. This also happens on the file `node_modules/pro-gallery-lib/dist/esm/common/utils/index.js`. :thinking:
