### ISSUE TITLE
Expand on click not working on the playground

### ISSUE THREAD

**Issue by jruiz94** [wix-incubator/pro-gallery#978]
I've tried to use the expand image on click from the playground but it doesn't work there. Also the documentation says to use the ExpandableProGallery component but I couldn't find it.

Is the documentation outdated?

**Comment by yhattav** [comment]
Hey, how did you try to activate the click to Expand?
Try going to Simulators down in the sidebar and toggling Click to Expand.
This works for me.

**Comment by jruiz94** [comment]
Thanks for taking the time to answer, I truly appreciate it. You're right, with that option in the "Simulators" section, now the playground works. However, when I generate the code for my gallery, the expand option doesn't work. As I mentioned, documentation says something about `ExpandableProGallery` but I couldn't find it. How can I make it work on my site?
Thanks again for the help

**Comment by yhattav** [comment]
So basically the Expand mode is not an integral part of the pro gallery. its just an external application that opens in a modal when the pro gallery's API sends the EVENTS.ITEM_CLICKED event.
The playground code listens to this event via the eventsListener function callback and opens the corresponding item in a modal that we designed.
You can use the pro gallery twice, one for the gallery itself and then again in a modal to display the expanded image, the design of the two will differ only by the props you use in the options object. 
You can use the props.options.layoutParams_structure_galleryLayout (number) to have a preset that we designed, one of which (  FULLSIZE: 9 ) is a full-sized gallery that shows only one item per gallery width.
playing with the galleryLayout number is a good start that you can add to.
