### ISSUE TITLE
The Title and Description (customHoverRenderer) do not show up

### ISSUE THREAD

**Issue by EngineNeo** [wix-incubator/pro-gallery#999]
I am adding a custom hover renderer:
``` const customInfoRenderer = (itemProps) => {
      if (window.innerWidth < 750)
        return (
          <span style={{ width: "80%" }} className="img-text">
            {itemProps.title}
            {itemProps.description}
          </span>
        );
      else
        return (
          <span style={{ width: "80%" }} className="img-text">
            {itemProps.title}
          </span>
        );
    };
```

This should be showing the title and description, but nothing shows up, it does not even show the div container in which the title and description should be in the div with the class name "gallery-item-hover-inner". I noticed it working in previous version(s) (4.0.4) (I am on v. (4.1.49), I am not sure if anything changed since then.

**Comment by yhattav** [comment]
Did you try this by rewriting it in the playground or was it passed in the props to the ProGallery component?

**Comment by EngineNeo** [comment]
> Did you try this by rewriting it in the playground or was it passed in the props to the ProGallery component?

I passed this in the prop to the ProGallery component, I resolved the issue by rolling back to an earlier build (v3.1.38). I'd also like to point out that custom image renderer was also unable to operate. If there is a new method or different name for custom components it should be reflected on the readme.

**Comment by EnochMichell** [comment]
I rolled back to an earlier build. I noticed that the custom image renderer could not operate as expected. If there have been updates or changes in the method or name for custom components, it would be helpful to see these reflected in the [footwear brand in pakistan](https://insignia.com.pk/) documentation.
